package com.example.murodjonrahimov.wecare.model;

/**
 * Created by murodjon.rahimov on 3/24/18.
 */

public class TermsAndConditions {

   public static String terms = "MOBILE APPLICATION TERMS AND CONDITIONS\n"
     + "\n"
     + "The Engage for Android mobile application (the “Application”), as made available through the Google Play store and is licensed, not sold, to you. As used herein, “You” and “Your” refer to the individual or entity that wishes to use the Application. Your license to this Application is subject to your prior acceptance of these Mobile Application Terms and Conditions (“Terms and Conditions”). In addition to the standard user terms and Program Policies applicable to use of the Google Play store, found here; https://play.google.com/intl/en_us/about/play-terms.html and here; https://play.google.com/about/android-developer-policies.html and you agree that all of these Terms and Conditions will apply to this Application. Your license to this Application under these Terms and conditions is granted by NavisHealth Solutions, Inc. (“Licensor”), not Google. Licensor reserves all ownership and intellectual property rights in and to the Application. This Application supports Android smart phone devices (the “Android Devices”), and enables users to access, review and use certain data (and perform certain actions with such data) where such data is provided by a connection to an instance of the Licensor’s Engage software (the “Engage Software”), an application licensed by a third party medical provider (“Your Provider”) under a separate agreement with Licensor.\n"
     + "\n"
     + "1. SCOPE OF LICENSE. This license granted to you for the Application by Licensor is limited to a non-exclusive, non-transferable, non-sublicensable, revocable limited license to run the Application on your Android Devices solely for the purpose of performing those functions and tasks available to you as an end user of the Application who: (a) connects to a properly licensed version of the Engage Software; and (b) is using any Android Device that you own or control. This license does not allow you to use the Application on any Android Device that you do not own or control, and you may not distribute or make the Application available over a network where it could be used by multiple devices at the same time. You may not rent, lease, lend, sell, redistribute or sublicense the Application. You may not copy (except as expressly permitted by this license and the Usage Rules), decompile, reverse engineer, disassemble, attempt to derive the source code of, modify or create derivative works of the Application, any updates, or any part thereof (except as and only to the extent any foregoing restriction is prohibited by applicable law. Any attempt to do so is a violation of the rights of the Licensor. If you breach this restriction, you may be subject to prosecution and damages. You are not permitted to use the Application for any purpose other than as expressly permitted under these Terms and Conditions. You acknowledge that the Licensor may audit your use of the Application.\n"
     + "\n"
     + "2. CONSENT TO USE OF DATA. You agree that Licensor and Your Provider may collect, store, process, maintain, upload, sync, transmit, share, disclose and use certain data and information, including but not limited to information or data regarding the characteristics or usage of your Android Device, system and application software, and peripherals, as well as personal information, user location data and user content (collectively, “User Data”) to facilitate the provision of the services or functionality of the Application, including but not limited to authentication, performance optimization, software updates, product support and other services to you related to the Application or to otherwise improve Licensor’s ability to provide other services (if any) to you related to the Application. You acknowledge that use of the Application may result in User Data being transmitted between your Android Device and a database service designated by Your Provider and/or transmitted or disclosed to or accessed by Licensor. Without limiting the foregoing, you acknowledge that: (a) information regarding the hardware model and the Android version of the Android Device on which you are running the Application may be collected, transmitted to and stored on a database server designated by Your Provider, may be transmitted to Licensor and may be used to make changes, updates or improvements to or optimize the performance of the Application or to otherwise inform future development; and (b) audit logs reflecting your logins, logouts and the activities you have accessed through your use of the Application may be generated in connection with your use of the Application may be collected, transmitted and stored on a database server designated by Your Provider. Your User Data may also be made available to Licensor for troubleshooting. BY CLICKING THE “ACCEPT” BUTTON, YOU EXPRESSLY CONSENT TO THE FOREGOING COLLECTION, STORAGE, PROCESSING, MAINTENANCE, UPLOADING, SYNCING, TRANSMITTING, SHARING, OR DISCLOSURE OF USER DATA. By continuing to use the Application, you indicate your continued consent to such collection, storage, processing maintenance, uploading, syncing, transmitting, sharing, or disclosure of User Data as well as collection, storage, transmission and use of data of the type and in the manner described in the Licensor’s Privacy Policy located at http://navishealth.com/about-us/privacy-policy\n"
     + "\n"
     + "3. PURPOSE. This Application is provided to educate you on health care and medical issues that may affect your daily lives. The Application allows you to view health-related information and arrange for clinical services and access additional services through Your Provider. This Application does not constitute the practice of any medical, nursing or other professional health care advice, diagnosis or treatment.\n"
     + "\n"
     + "4. THIS APPLICATION DOES NOT PROVIDE MEDICAL ADVICE. The contents of the Application, such as text, graphics, images, data, graphs, audio, videos, computer programs and other material and information (collectively the \"Content\"), are for informational purposes only. THE CONTENT PROVIDED IN THIS APPLICATION IS NOT A SUBSTITUTE FOR THE ADVICE OF YOUR PROFESSIONAL PHYSICIAN OR OTHER QUALIFIED HEALTH CARE PROFESSIONAL. ALWAYS SEEK THE ADVICE OF YOUR PHYSICIAN OR OTHER QUALIFIED HEALTH CARE PROFESSIONAL WITH ANY QUESTIONS YOU MAY HAVE REGARDING A MEDICAL SYMPTOM OR A MEDICAL CONDITION. NEVER DISREGARD PROFESSIONAL MEDICAL ADVICE OR DELAY IN SEEKING IT BECAUSE OF SOMETHING YOU HAVE READ OR SEEN IN THIS APPLICATION. IF YOU THINK YOU HAVE A MEDICAL OR PSYCHIATRIC EMERGENCY, CALL 911 OR GO TO THE NEAREST HOSPITAL.\n"
     + "\n"
     + "5. CHANGES AND UPDATES. LICENSOR may revise the information in this Application, or otherwise change or update the Application including these Terms and Conditions, without notice to you. Licensor may also make improvements and/or changes in services and functionalities or add new features at any time without notice. We encourage you to periodically read these Terms and Conditions to see if there have been any changes to our policies that may affect you. Your continued use of this Application will signify your continued agreement to these Terms and Conditions as they may be revised.\n"
     + "\n"
     + "6. LINKS TO THIRD PARTY APPLICATIONS. The Application provides links to other websites, applications, or content that are not owned or controlled by the Licensor, including Your Provider (\"Third Party Providers\"). These links are intended to connect you easily to additional sources of health information or third party services that may be of interest to you. We may not have any business relationship with the Third Party Provider that controls this type of content and such links are offered only as a convenience to you. Licensor is not responsible for the content, security or the privacy practices of Third Party Providers. Please review the privacy statement and any terms of use of each Third Party Providers you use. Unless we specifically advise you otherwise, links to Third Party Providers do not constitute or imply endorsement by the Licensor of those sites, the information they contain or any products or services they describe. Licensor does not receive payment or other remuneration in exchange for you linking to or using any information provided by a Third Party Provider.\n"
     + "\n"
     + "7. PASSWORDS. Licensor has several tools that allow you to record and store information. You are responsible for taking all reasonable steps to ensure that no unauthorized person shall have access to the Application password or account. It is your sole responsibility to (a) control the disclosure and use of your activation codes and password; (b) authorize, monitor, and control access to and use of the Application account and password; and (c) promptly inform the Licensor of any need to deactivate a password.\n"
     + "\n"
     + "8. SECURITY AND CONFIDENTIALITY. We afford the same degree of confidentiality to medical information stored on the Application as is given to health information stored by Licensor in any other medium. Licensor is committed to protecting the confidentiality of your health information. We limit our employees’ access and ability to enter or view health information based upon their role in your care. We have taken steps to make all health information we receive as secure as possible against unauthorized access, use, or disclosure.\n"
     + "\n"
     + "DISCLAIMER. YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE APPLICATION AND YOUR RELIANCE ON THE OPERATION, OUTPUT OR RESULTS OF THE APPLICATION IS AT YOUR SOLE RISK AND THAT THE ENTIRE RISK AS TO SATIFACTORY QUALITY, PERFORMANCE, ACCURACY AND EFFORT IS WITH YOU. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE APPLICATION AND ANY SERVICES PERFORMED OR PROVIDED BY THE APPLICATION (THE “APPLICATION SERVICES”) ARE PORVIDED “AS IS” AND “AS “AVAILABLE”, WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH REPSECT TO THE APPLICATION AND ANY APPLICATION SERVICES, EITHER EXPRESS, IMPLIED OR STAUTTORY, INCLUDING BUT NOT LIMITED TO, THE IMPIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, OF SATISFACTORY QUALITY, OF FITNESS FOR A PARTICULAR PURPOSE, OR ACCURACY, OF QUIET ENJOYMENT, AND NON-INFRINGEMENT OF THIRD PARTY RIGHTS. LICENSOR DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE APPLICATION, THAT THE FUNCTIONS CONTAINED IN, OR APPLICATION SERVICES PERFORMED OR PROVIDED BY, THE APPLICATION WILL MEET YOUR REQUIREMENTS, THAT THE OPERATION OF THE APPLICATION OR APPLICATION SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT DEFECTS IN THE APPLICATION OR APPLICATION SERVICES WILL BE CORRECTED. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY LICENSOR , ITS AUTHORIZED REPRESENTATIVE, OR YOUR PROVIDER SHALL CREATE A WARRANTY. SHOULD THE APPLICATION OR APPLICATION SERVICES PROVE DEFECTIVE, YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION. SOME JURISCTIIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU.\n"
     + "\n"
     + "9. LIMITATION ON LIABILITY. LICENSOR, ITS AFFILIATES, AND SUPPLIERS ARE NEITHER RESPONSIBLE NOR LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE, OR OTHER DAMAGES (INCLUDING, WITHOUT LIMITATION, THOSE RESULTING FROM LOST PROFITS, LOST DATA, OR BUSINESS INTERRUPTION) ARISING OUT OF OR RELATING IN ANY WAY TO THE APPLICATION, SITE-RELATED SERVICES AND PRODUCTS, CONTENT OR INFORMATION CONTAINED WITHIN THE APPLICATION, AND/OR ANY THIRD PARTY WEB SITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY AND WHETHER OR NOT ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. YOUR SOLE REMEDY FOR DISSATISFACTION WITH THIS APPLICATION, APPLICATION SERVICES, AND/OR THIRD PARTY WEB SITES IS TO STOP USING THE APPLICATION AND/OR THOSE SERVICES. THESE TERMS AND CONDITIONS ARE GOVERNED BY CALIFORNIA LAW WITHOUT REGARD TO ITS PRINCIPLES OF CONFLICTS OF LAW. IF ANY VERSION OF THE UNIFORM COMPUTER INFORMATION TRANSACTIONS ACT (UCITA) IS ENACTED AS PART OF THE LAW OF CALIFORNIA, THAT STATUTE SHALL NOT GOVERN ANY ASPECT OF THESE TERMS AND CONDITIONS.\n"
     + "\n"
     + "10. PROHIBITED ACTIVITY. You agree that you will not upload or transmit any communications or content of any type (including secure messaging) that infringe upon, misappropriate or violate any rights of any party. In consideration of being allowed to use the Application, you agree that the following actions shall constitute a material breach of these Terms and Conditions: (a) signing on as or pretending to be another person; (b) using secure messaging for any purpose in violation of local, state, national, international laws or posted Licensor policies; (c) transmitting material that infringes or violates the intellectual property rights of others or the privacy or publicity rights of others; (d) transmitting material that is unlawful, obscene, defamatory, predatory of minors, threatening, harassing, abusive, slanderous, or hateful to any person (including Licensor personnel) or entity as determined by Licensor in its sole discretion; (e) using interactive services in a way that is intended to harm, or a reasonable person would understand would likely result in harm, to the user or others; (f) collecting information about others, including e-mail addresses; (g) intentionally distributing viruses or other harmful computer code; and (i) Licensor expressly reserves the right, in its sole discretion, to terminate a User's access to the Application due to any act delineated above, or any act that would constitute a violation of these Terms and Conditions.\n"
     + "\n"
     + "11. TERMINATION. These Terms and Conditions are effective until terminated by you or Licensor. Your rights under these Terms and Conditions will terminate automatically without notice from Licensor if you fail to comply with any of these Terms and Conditions. Upon termination, you shall cease all use of the Application, and destroy all copies, full or partial, of the Application.\n"
     + "\n"
     + "12. COPYRIGHTS. Except as otherwise indicated, all content on the Application, including text, graphics, logos, button icons, photos, images, forms, audio, video, questionnaires, and software, is the property of Licensor or its licensors and is protected by United States and international copyright laws. Licensor allows you to view or download a single copy of the material on the Application solely for your personal, noncommercial use. The compilation of all content on the Application is the exclusive property of Licensor or its licensors and is protected by United States and international copyright laws. Unless specifically authorized in writing by Licensor, any use of these materials, or of any materials contributed to the Application by entities other than Licensor, on any other Web site or networked computer environment for any purpose is prohibited.\n"
     + "\n"
     + "13. TRADEMARKS AND SERVICE MARKS. Other proprietary marks of Licensor or third parties may be designated as such from time to time on the Application through use of the TM, SM, or ® symbols. Application Users are not authorized to make any use of the Marks or the proprietary marks of third parties, including but not limited to, as metatags or in any other fashion that may create a false or misleading impression of affiliation or sponsorship with or by Licensor or the applicable third party.\n"
     + "\n"
     + "14. EXPORT RESTRICTIONS. You may not use or otherwise export or re-export the Application except as authorized by United States law and the laws of the jurisdiction in which the Application was obtained. In particular, but without limitation, the Application may not be exported or re-exported (a) into any U.S. embargoed countries or (b) to anyone on the U.S. Treasury Department’s list of Specially Designated Nationals or the U.S. Department of Commerce Denied Person’s List or Entity List. By using the Application, you represent and warrant that you are not located in any such country or on any such list. You also agree that you will not use the Application for any purpose prohibited by United States law, including without limitation, the development, design, manufacture or production of nuclear, missiles or chemical or biological weapons.\n"
     + "\n"
     + "15. LICENSOR. The Licensor of the Application is NavisHeath Solutions, Inc. and is located at 2560 Mission College Blvd. Suite 140, Santa Clara, California 95054. If you have any questions about the Application, please send an email to support@navishealth.com.\n"
     + "\n"
     + "16. THIRD PARTY BENEFICIARY. You acknowledge and agree that Google and its subsidiaries are third party beneficiaries to these Terms and Conditions and that upon your acceptance of these Terms and Conditions, Google will have the right (and will deemed to have accepted the right) to enforce these Terms and Conditions against you as a third party beneficiary thereof.\n"
     + "\n"
     + "\n"
     + "\n"
     + "Last updated: 4/3/2015";
}
